name: Delete old contents

on: [push]
#   schedule:
#     - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Call API to delete old contents
        env:
          API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
          API_URL: ${{ secrets.API_URL }}
        run: |
          curl -X POST -H "Authorization: Bearer $API_ACCESS_TOKEN" --fail $API_URL
