name: test HTTPie

on: [push]
#   schedule:
#     - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: wei/curl@v1
      with:
        args: -X POST https://httpbin.org/post
