name: Call API

on: [push]
#   schedule:
#     - cron: '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Test
      uses: wei/curl@v1
      env:
        API_ACCESS_TOKEN: ${{ secrets.API_ACCESS_TOKEN }}
        API_URL: ${{ secrets.API_URL }}
      with:
        args: "-X POST -H \"Authorization: Bearer $API_ACCESS_TOKEN\" \"$API_URL\" "
